# Generated by Django 4.1.4 on 2023-01-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_bodyshape_shape_alter_day_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shape",
            name="biceps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shape",
            name="calf",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shape",
            name="chest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shape",
            name="forearm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shape",
            name="glutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shape",
            name="neck",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shape",
            name="shoulders",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shape",
            name="thighs",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
