# Generated by Django 4.1.4 on 2023-01-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_shape_biceps_shape_calf_shape_chest_shape_forearm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Easy",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="training",
            name="program",
            field=models.ManyToManyField(to="app.program"),
        ),
    ]
