# Generated by Django 4.1.4 on 2023-01-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_training_program_alter_program_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.program",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Easy",
                max_length=20,
            ),
        ),
    ]
