# Generated by Django 4.1.4 on 2023-01-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_training_program_alter_program_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="rest",
            field=models.IntegerField(default=30),
        ),
    ]
