# Generated by Django 4.1.4 on 2023-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_exercise_rest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="muscles",
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscle",
            field=models.CharField(default="muscle", max_length=20),
        ),
        migrations.DeleteModel(
            name="Muscle",
        ),
    ]
