# Generated by Django 4.1.4 on 2023-01-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_training_muscles_exercise_muscle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="exercises",
            field=models.ManyToManyField(to="app.exercise"),
        ),
    ]
