# Generated by Django 4.1.4 on 2023-01-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_water_delete_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.program"
            ),
        ),
    ]
