# Generated by Django 4.1.4 on 2023-01-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
