# Generated by Django 4.1.4 on 2023-01-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_user_picture_user_image_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="avatars"),
        ),
    ]
