# Generated by Django 4.1.4 on 2023-01-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="picture",
        ),
        migrations.RemoveField(
            model_name="user",
            name="image_data",
        ),
    ]
