# Generated by Django 4.1.4 on 2023-01-05 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_rename_image_user_picture_remove_user_image_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_data", models.CharField(max_length=999999999)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="image_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.image",
            ),
        ),
    ]
