# Generated by Django 4.1.4 on 2023-01-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_image_user_image_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image_data",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
