# Generated by Django 4.1.4 on 2023-01-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_imagesforuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImagesForUser",
        ),
    ]
