# Generated by Django 4.1.4 on 2023-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_delete_imagesforuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="base64",
            field=models.CharField(blank=True, max_length=9999999, null=True),
        ),
    ]
