# Generated by Django 4.1.4 on 2023-01-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_user_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="picture",
        ),
    ]
